<a href="https://colab.research.google.com/github/wsm9175/DeepLearningStudy/blob/main/FP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Activation Function 실습

1-3-1 Activation Layers

In [ ]:
import tensorflow as tf

#max - Returns the max of x and y (i.e. x > y ? x : y)
#Computes exponential of x element-wise.
from tensorflow.math import exp, maximum  
from tensorflow.keras.layers import Activation

# input setting  tf.random.normal - Outputs random values from a normal distribution
x = tf.random.normal(shape=(1, 5))

# activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation(tensorflow)
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)

# forward propagation(manual)
y_sigmoid_man = 1 / (1+exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(x, 0)

print(f"x:{x.shape}\n{x.numpy()}") # 1, 5
print(f"sigmoid(Tensorflow): {y_sigmoid_tf.shape}\n{y_sigmoid_tf.numpy()}") # 1, 5
print(f"sigmoid(manual): {y_sigmoid_man.shape}\n{y_sigmoid_man.numpy()}", end="\n\n") # 1, 5

print(f"Tanh(Tensorflow): {y_tanh_tf.shape}\n{y_tanh_tf.numpy()}")
print(f"Tanh(manual): {y_tanh_man.shape}\n{y_tanh_man.numpy()}", end="\n\n")

print(f"relu(Tensorflow): {y_relu_tf.shape}\n{y_relu_tf.numpy()}")
print(f"relu(manual): {y_relu_man.shape}\n{y_relu_man.numpy()}")


x:(1, 5)
[[-1.0090201  1.1141306  0.6600343 -0.7265979 -0.7278725]]
sigmoid(Tensorflow): (1, 5)
[[0.2671717  0.7528984  0.6592681  0.32594174 0.32566178]]
sigmoid(manual): (1, 5)
[[0.26717168 0.7528984  0.65926814 0.32594174 0.32566175]]

Tanh(Tensorflow): (1, 5)
[[-0.7653565   0.80551773  0.57838625 -0.6209796  -0.62176204]]
Tanh(manual): (1, 5)
[[-0.76535636  0.8055176   0.5783862  -0.6209796  -0.62176204]]

relu(Tensorflow): (1, 5)
[[0.        1.1141306 0.6600343 0.        0.       ]]
relu(manual): (1, 5)
[[0.        1.1141306 0.6600343 0.        0.       ]]


Code. 1-3-2: Activation in Dense Layer

In [ ]:
import tensorflow as tf
from tensorflow.math import maximum
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1, 5)) # input setting

# artificial neurons
dense_sigmoid = Dense(units=1, activation='sigmoid') # unit - Artificial neuron
dense_tanh = Dense(units=1, activation='tanh')
dense_relu = Dense(units=1, activation='relu')

# forward propagaion
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)

print(f"AN with sigmoid: {y_sigmoid.shape}\n{y_sigmoid.numpy()}") 
print(f"AN with tanh: {y_tanh.shape}\n{y_tanh.numpy()}")
print(f"An with relu: {y_relu.shape}\n{y_relu.numpy()}")

print('\n===================================\n')

# forward propagaion(manual)
# Dense_sigmoid로 부터 Weight, Bias를 가져옴
W, B = dense_sigmoid.get_weights()
print(f'W{W} \nB{B} \nx{x}') # W - (5, 1), B - (1, ), x - (1, 5)
# Weight, Bias를 바탕으로 input matrix와 행렬 곱 수행 및 Bias를 더해줌
z = tf.linalg.matmul(x, W) + B # matmul: 행렬 곱  
# Activation Function - Sigmoid
a = 1 / (1+exp(-z))
print(a)

AN with sigmoid: (1, 1)
[[0.609048]]
AN with tanh: (1, 1)
[[0.73754156]]
An with relu: (1, 1)
[[1.4351355]]


W[[ 0.14740849]
 [ 0.7600348 ]
 [-0.9701698 ]
 [-0.09509254]
 [-0.45259237]] 
B[0.] 
x[[-2.6182420e+00  5.5536658e-01 -3.8652912e-01 -3.3534023e-01
  -6.1476888e-04]]
tf.Tensor([[0.609048]], shape=(1, 1), dtype=float32)


In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

activation = 'sigmoid'

x = tf.random.uniform(shape=(1, 10))

dense = Dense(units=1, activation=activation) # affine + activation
              
y_tf = dense(x)
print(y_tf)

W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B
y_man = 1/(1+exp(-y_man))
print(y_man)


tf.Tensor([[0.45120633]], shape=(1, 1), dtype=float32)
tf.Tensor([[0.45120633]], shape=(1, 1), dtype=float32)


shapes of Dense Layers

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch
print(x.shape)

dense = Dense(units=1, activation='relu')
y = dense(x)

# Wight, Bias는 input 행의 개수에 영향을 받지 않는다.
W, B = dense.get_weights()
print("Shape of x: ", x.shape) # (8, 10)
print("Shape of W: ", W.shape) # (Input_feature, the number of neurons)) -> (10,1)
print("Shape of B: ", B.shape) # (the number of neurons) -> (10, )

(8, 10)
Shape of x:  (8, 10)
Shape of W:  (10, 1)
Shape of B:  (1,)


Code. 1-5-2 Output Calculation

In [2]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch

dense = Dense(units=1, activation = 'sigmoid') # imp, an AN
y_tf = dense(x) # foward propagation Tensor

W, B = dense.get_weights()

# manual
y_man = tf.linalg.matmul(x, W) + B
y_man = 1/(1+tf.math.exp(-y_man))

#print results
print("Output(Tensorflow): \n", y_tf.numpy())
print("Output(Manual): \n", y_man.numpy())
print(tf.math.equal(y_tf, y_man))

Output(Tensorflow): 
 [[0.16918442]
 [0.8744273 ]
 [0.8723631 ]
 [0.3687498 ]
 [0.4484246 ]
 [0.7458326 ]
 [0.48593822]
 [0.8058391 ]]
Output(Manual): 
 [[0.1691844 ]
 [0.87442726]
 [0.87236303]
 [0.3687498 ]
 [0.44842464]
 [0.7458326 ]
 [0.48593825]
 [0.8058391 ]]
tf.Tensor(
[[False]
 [False]
 [False]
 [ True]
 [False]
 [ True]
 [False]
 [ True]], shape=(8, 1), dtype=bool)


Code.2-1-1: Shapes of Dense Layers

In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 # N - batchsize
X = tf.random.normal(shape=(N, n_feature)) # (1, 10) 행렬

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()

print('==== Input/Weight/bias ====')
print('X: ', X.shape) # 8, 10
print('W: ', W.shape) # 10, 3
print('B: ', B.shape) # 10, 
print('Y: ', Y.shape) # 8, 3

print(X.numpy())
print(W)
print(Y.numpy())

==== Input/Weight/bias ====
X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)
[[-0.38205552 -0.45030057 -0.2573847   0.01237032  1.3987805   0.09815046
   0.36869457 -1.3067293  -0.41829124 -0.4291312 ]
 [-0.7919713   0.25941178 -0.40508628 -0.2745618  -0.5430084   0.5814999
   0.53034085  1.9772941   0.93749815 -1.4025333 ]
 [-1.2837842  -1.6288426   0.9276947  -1.7925206   0.9474805   0.3818545
   3.0268989   0.0290732   0.812758    0.5514525 ]
 [ 1.7728289   0.22777899 -0.3783955   0.28738135  0.26365623 -1.0954878
   0.90043986  0.6281416  -0.4667178  -0.27795398]
 [-0.04531534 -0.8555465  -0.81288534 -1.2335558  -0.37511435  0.8695283
   1.3844451   1.1177456   0.9289346   0.63200563]
 [-0.7801288  -0.26284257  0.4599856  -1.2211821  -0.46178487 -1.3548064
   0.7739596   0.08491572 -0.59735787 -0.5004451 ]
 [ 0.65903586  0.96519375 -0.9963751  -0.26402247 -1.382591   -1.6495672
   0.03229915  0.9127999   1.1559516   0.06113651]
 [-0.505244   -0.64534897  0.35026267  0.5792075  -0.546761

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
import numpy as np

from tensorflow.math import exp 
from tensorflow.linalg import matmul

N, n_feature = 4,10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(Tensorflow): \n", Y_tf.numpy())

# manual
z = matmul(X, W) + B # Affine 
y_man_matmul = 1/(1+exp(-z)) # Activation
print("Y(with matrix multiplication: \n", y_man_matmul.numpy())

# calculate with matrix multiplication
y_man_vec = np.zeros(shape=(N, n_neuron)) # neuron에서의 연산 결과: (N, n_neuron)

for x_idx in range(N):
  x = X[x_idx] # 하나의 input data씩 빼옴

  for nu_idx in range(n_neuron):
    w, b = W[:, nu_idx], B[nu_idx] # W - (10, 3), B - (10, ), 

    z = tf.reduce_sum(x * w) + b
    a = 1/(1+np.exp(-z))
    y_man_vec[x_idx, nu_idx] = a

  print(y_man_vec)

Y(Tensorflow): 
 [[0.22057503 0.76621556 0.4507358 ]
 [0.5104988  0.2198754  0.29087013]
 [0.8218975  0.5118218  0.19009319]
 [0.87203234 0.86666894 0.02511972]]
Y(with matrix multiplication: 
 [[0.220575   0.7662156  0.4507358 ]
 [0.51049876 0.21987538 0.29087016]
 [0.8218975  0.51182187 0.19009316]
 [0.8720324  0.866669   0.02511972]]


2-2 Cascaded dense Layers

2-2-1: Shapes of Cascaded Dense layers

In [7]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

W1, B1 = dense1.get_weights() 
W2, B2 = dense2.get_weights()

print(f"W1: {W1.shape}\n")
print(f"B1: {B1.shape}\n")
print(f"A1: {A1.shape}\n")

print(f"W2: {W2.shape}\n")
print(f"B2: {B2.shape}\n")
print(f"Y: {Y.shape}")

W1: (10, 3)

B1: (3,)

A1: (4, 3)

W2: (3, 5)

B2: (5,)

Y: (4, 5)


Code.2-2-2: Dense Layers with python List

In [9]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

dense_layers = list()

for n_neuron in n_neurons:
  dense = Dense(units = n_neuron, activation='relu')
  dense_layers.append(dense)

for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  print("After dense layer ", dense_idx)
  print(X.shape, "\n")

After dense layer  0
(4, 10) 

After dense layer  1
(4, 20) 

After dense layer  2
(4, 30) 

After dense layer  3
(4, 40) 

After dense layer  4
(4, 50) 

After dense layer  5
(4, 60) 

After dense layer  6
(4, 70) 

After dense layer  7
(4, 80) 

After dense layer  8
(4, 90) 

After dense layer  9
(4, 100) 



In [24]:
import tensorflow as tf

from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X)

n_neurons = [10, 20, 30]

dense_layers = list()
for n_neuron in n_neurons:
  dense = Dense(units = n_neuron, activation="sigmoid")
  dense_layers.append(dense)

# forward propagation(Tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
  X = dense(X)
  w, b = dense.get_weights()
  print(w.shape)
  W.append(w)
  B.append(b)

print("Y(Tensor) ", X.numpy())
# forward propagation(Manual)
for layer_idx in range(len(n_neurons)):
  w, b = W[layer_idx], B[layer_idx]
  print(w.shape)
  X_cp = matmul(X_cp, w) + b
  X_cp = 1/(1+exp(-X_cp)) # activation sigmoid

# print("Y(matmul): ", X_cp.numpy())

(10, 10)
(10, 20)
(20, 30)
20


2-3: Model Implementation

Code.2-3-1: Model Implementation with Sequential Method

In [27]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

n_neurons = [3, 4, 5, 6]

# list 활용
model = list()
for n_neuron in n_neurons:
  model.append(Dense(units = n_neuron, activation='sigmoid'))

#Sequential 활용
model = Sequential()
for n_neuron in n_neurons:
  model.add(Dense(units=n_neuron, activation='sigmoid'))

model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

In [28]:
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Model

class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')
  
model = TestModel()
print(model.dense1)
print(model.dense2)

In [38]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Model

X = tf.random.normal(shape=(4, 10))

#Sequential method
model = Sequential()
model.add(Dense(units=10, activation='sigmoid'))
model.add(Dense(units=20, activation='sigmoid'))

Y = model(X)

# Model-subclassing
class TestModel(Model):
  def __init__(self):
    super(TestModel, self).__init__()

    self.dense1 = Dense(units=10, activation='sigmoid')
    self.dense2 = Dense(units=20, activation='sigmoid')

  def __call__(self, x):
    x = self.dense1(x)
    x = self.dense2(x)
    W, B = dense2.get_weights()
    print("W1, B1: ", W, B)
    return x

model = TestModel()
Y = model(X)

W1, B1:  [array([[ 0.24165428, -0.3595832 ,  0.2361126 ,  0.5297321 , -0.48347393,
         0.21606952, -0.07336351,  0.14820504,  0.41083413, -0.00087374],
       [ 0.31512374,  0.07172662,  0.01387113, -0.4433536 , -0.3454167 ,
        -0.3809709 , -0.40791458,  0.3373593 , -0.36700147, -0.00291121],
       [ 0.2638511 , -0.363146  , -0.02388936, -0.3204531 , -0.5301211 ,
        -0.47891825, -0.23174298,  0.22747016,  0.413355  , -0.00759327],
       [ 0.47039783,  0.2660706 ,  0.46870768,  0.336159  , -0.28244647,
         0.4942317 , -0.47054043, -0.18768403,  0.36063105, -0.2108579 ],
       [ 0.1654346 , -0.37503284,  0.3085791 ,  0.16584462, -0.31636795,
         0.49002278, -0.31850097,  0.2920701 , -0.52467513,  0.01276153],
       [ 0.0087052 , -0.11159855, -0.4937092 , -0.2374559 ,  0.49185085,
        -0.3074802 , -0.4504702 ,  0.52938056,  0.3717714 , -0.19589445],
       [ 0.4556321 ,  0.20078778,  0.02391326,  0.34223312, -0.13242239,
        -0.21748507, -0.4497127 , -