<a href="https://colab.research.google.com/github/wsm9175/DeepLearningStudy/blob/main/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Numpy는 numerical Python의 줄임말이다. 파이썬에서 산술 계산식을 위한 가장 중요한 패키지중 하나이다. 과학 계산을 위한 대부분의 패키지는 Numpy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.

Numpy 라이브러리 import

In [1]:
import numpy as np

# Numpy ndarray
Numpy의 핵심 기능 중 하나는 ndarray라고 하는 N차원 배열 객체인데 파이썬에서 할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조이다.

In [ ]:
a = np.array([1, 2, 3])
print(a, type(a))

[1 2 3] <class 'numpy.ndarray'>


List와 비교

In [ ]:
L = [1, 2, 3]
A = np.array([1, 2, 3])
print(L)
print(A)

[1, 2, 3]
[1 2 3]


In [ ]:
A

array([1, 2, 3])

In [ ]:
for item in L:
  print(item)

1
2
3


In [ ]:
for item in A:
  print(item)

1
2
3


In [ ]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [ ]:
A = np.append(A, 4)
print(A)

[1 2 3 4]


In [ ]:
L = L + [5]
print(L)

[1, 2, 3, 4, 5, 5, 5]


In [ ]:
A = A + np.array([5]) # broadcasting 
print(A)

[6 7 8 9]


In [ ]:
#list의 모든 원소를 2배로 만들기
L  = [1,2 ,3]
L2 = []
for item in L:
  L2.append(item*2)
print(L2)

[2, 4, 6]


In [ ]:
# ndarray의 모든 원소 2배로 만들기
A = np.array(L)
A2 = A*2
print(A2)

[2 4 6]


In [ ]:
L * 2

[1, 2, 3, 1, 2, 3]

# 배열
numpy 배열은 모두 같은 유형의 값이며 음수가 아닌 정수의 튜플로 인덱싱된다. 차원의 수는 배열 랭크이다. 배열의 shape은 각 차원별 배열 크기의 튜플이다. 중첩 된 파이썬 리스트로부터 numpy 배열을 초기화 할 수 있고 대괄호를 사용하여 요소에 접근 할 수 있다. 

In [ ]:
a = np.array([1, 2, 3])
print(a)
print(type(a), a.ndim, a.shape, a.dtype)

[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int64


In [ ]:
b = np.asarray(a) # 얕은 복사
print(b)

[9 2 3]


In [ ]:
b[0] = 9
print(a)
print(b)

[9 2 3]
[9 2 3]


In [ ]:
c = np.array(a) # 깊은 복사
print(c)

[9 2 3]


In [ ]:
c[0] = 1 
print(a)
print(b)
print(c)

[9 2 3]
[9 2 3]
[1 2 3]


In [ ]:
a = np.zeros((3, 4)) # 기본적으로 float64 type을 가짐
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
b = np.ones((5, 2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
c = np.full((2, 3), 4)
print(c)

[[4 4 4]
 [4 4 4]]


In [ ]:
d = np.empty((3, 3))
print(d)

[[4.65834691e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


In [ ]:
e = np.zeros_like(a) # _like 모양만 가져옴
f = np.ones_like(a)
g = np.full_like(a, 2)
h = np.empty_like(a)
print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[4.65834691e-310 0.00000000e+000 8.56215764e-321 4.65834571e-310]
 [6.91446911e-310 4.65834571e-310 6.91446911e-310 6.91446911e-310]
 [0.00000000e+000 1.48219694e-323 2.12199579e-314 5.43472210e-323]]


In [ ]:
# 항등 행렬을 만듬
i = np.eye(3)
j = np.identity(3)
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
k = np.arange(10)
print(k)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
K = np.arange(1, 11)
print(K)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
k = np.arange(10, 0, -1)
print(k)

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# uniform distribution
l = np.random.rand(2, 2)
print(l)

[[0.53911658 0.75881438]
 [0.18785416 0.48324202]]


In [ ]:
# normal distribution
m = np.random.randn(2, 2) # 평균=0, 표준편차=1 - 표준정규분포
print(m)

[[ 0.50432957  0.89021115]
 [-1.8330855   0.12395812]]


배열의 dtype

In [ ]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3], dtype=np.float64)
c = np.array([1, 2, 3], dtype=np.int64)

print(a.dtype, b.dtype, c.dtype)

int64 float64 int64


In [ ]:
d = np.array([1, 2, 3], dtype='i1')
e = np.array([1, 2, 3], dtype='i2')
f = np.array([1, 2, 3], dtype='i4')
g = np.array([1, 2, 3], dtype='i8')

print(d.dtype, e.dtype, f.dtype,g.dtype)

int8 int16 int32 int64


In [ ]:
# unsigned
d = np.array([1, 2, 3], dtype='u1')
e = np.array([1, 2, 3], dtype='u2')
f = np.array([1, 2, 3], dtype='u4')
g = np.array([1, 2, 3], dtype='u8')

print(d.dtype, e.dtype, f.dtype,g.dtype)

uint8 uint16 uint32 uint64


In [ ]:
h = np.array([1, 2, 3], dtype='f2')
i = np.array([1, 2, 3], dtype='f4')
j = np.array([1, 2, 3], dtype='f8')
k = np.array([1, 2, 3], dtype='f16')

print(h.dtype, i.dtype, j.dtype,k.dtype)

float16 float32 float64 float128


In [ ]:
i = np.array([1, 2, 3], dtype='f')
j = np.array([1, 2, 3], dtype='d')
k = np.array([1, 2, 3], dtype='g')

print(h.dtype, i.dtype, j.dtype,k.dtype)

float16 float32 float64 float128


In [ ]:
i.astype(np.int32)
print(i.dtype)

int32


In [ ]:
j.astype(i.dtype)
print(i.dtype)

int32


# 배열 indexing(색인)과 slicing(슬라이싱)

indexing, slicing 기본

In [ ]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# indexing
print(a[5])

5


In [ ]:
# slicing
print(a[5:8])

[5 6 7]


In [ ]:
print(a[-1])

9


In [ ]:
print(a[5:-1]) #-1 맨 마지막 전

[5 6 7 8]


In [ ]:
a[5:8] = 10
print(a)

[ 0  1  2  3  4 10 10 10  8  9]


# indexing과 slicing의 차이

indexing을 사용하면 항상 랭크가 감소한다. 반면 slicing을 사용하면 차원이 유지된다.

In [2]:
b = np.arange(1, 13)
# b = b.reshape(3, 4)
print(b)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [3]:
indexing = b[1]
slicing = b[1:2]
print(indexing, indexing.shape, indexing.ndim)
print(slicing, slicing.shape, slicing.ndim)

2 () 0
[2] (1,) 1


indexing과 slicing을 함께 사용할 때도 마찬가지이다. indexing의 개수만큼 랭크는 감소한다.

In [4]:
b = b.reshape(3, 4)
print(b)
print(b.shape)
print(b.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [ ]:
row_r1 = b[1, :]
row_r2 = b[1:2, :]
print(row_r1, row_r1.shape, row_r1.ndim) # dimension 감소
print(row_r2, row_r2.shape, row_r2.ndim) # dimension 그대로

[5 6 7 8] (4,) 1
[[5 6 7 8]] (1, 4) 2


slicing examples

In [5]:
c = np.arange(24).reshape(2, 3, 4)
print(c)
print(c.shape)
c.ndim

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


3

In [ ]:
print(c[:,:,:1])
print(c[...,:1]) # ... - 앞차원을 전부 다 가져옴

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [7]:
print(c[0:1])
print(c[0::-1])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


boolean indexing

In [ ]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
bool_idx = (c > 10)
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [ ]:
print(c[bool_idx]) # 차원을 무시함

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [ ]:
c[c>10] = -1
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [-1 -1 -1 -1]]]


fancy indexing

In [ ]:
d = np.arange(8).reshape(8, -1)
print(d, d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [ ]:
d = np.hstack((d, d, d, d)) # 원소를 옆으로 붙임
print(d, d.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [ ]:
print(d[[3, 5, 1, 0]]) # 3, 5, 1, 0행을 가져와 새로운 행렬을 만듬

[[3 3 3 3]
 [5 5 5 5]
 [1 1 1 1]
 [0 0 0 0]]


In [ ]:
print(d[[-3, -5, -7]])

[[5 5 5 5]
 [3 3 3 3]
 [1 1 1 1]]


In [ ]:
e = np.arange(32).reshape(8, 4)
print(e, e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [ ]:
print(e[[1, 5, 7, 2]])

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]


In [ ]:
print(e[[1, 5, 7, 2],[0,3,1,2]]) # (1, 0), (5, 3)...

[ 4 23 29 10]


In [ ]:
print(e[[1, 5, 7, 2]][:, [0, 3, 1, 2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


Transpose

In [8]:
f = np.arange(16).reshape(2, 2, 4)
print(f, f.shape, f.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4) 3


In [ ]:
print(f.transpose(2, 1, 0))

[[[ 0  8]
  [ 4 12]]

 [[ 1  9]
  [ 5 13]]

 [[ 2 10]
  [ 6 14]]

 [[ 3 11]
  [ 7 15]]]


In [ ]:
print(f.swapaxes(0, 1)) # 0번축과 1번축의 순서를 바꿈

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


Numpy 연산

In [ ]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [ ]:
print(x + y)
print(np.add(x, y)) # add - universal function

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
print(x-y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [ ]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [ ]:
print(x /y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# 행렬 곱
print(x @ y)
print(np.matmul(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [ ]:
z = np.arange(1, 11).reshape(2, 5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
print(np.sum(z))

55


In [ ]:
sum1 = np.sum(z, axis=0)
sum2 = np.sum(z, axis=1)
sum3 = np.sum(z, axis=-1)
print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

[ 7  9 11 13 15] (5,)
[15 40] (2,)
[15 40] (2,)


axis는 각 배열의 차원에 해당되는 index이다.

axis=0에 대해 sum을 하라는 것은 0번 축 혹은 차원이 없어지는 방향으로 원소들을 모두 더하라는 얘기이다.

즉, 위 예에서 sum1의 경우, z[0,:]+z[1,:]의 연산을 하라는 의미이고,

sum2의 경우에는 z[:,0]+z[:,1]+z[:,2]+z[:,3]+z[:,4]의 연산을 하라는 의미이다.

In [ ]:
print(z[0,:]+z[1,:])

[ 7  9 11 13 15]


In [ ]:
print(z[:,0]+z[:,1]+z[:,2]+z[:,3]+z[:,4])

[15 40]


# Broadcasting

Broadcasting은 numpy가 산술 연산을 수행 할 때 다른 모양의 배열로 작업 할 수 있게 해주는 강력한 메커니즘이다. 종종 더 작은 배열과 더 큰 배열이 있을 때 더 작은 배열을 여러번 사용하여 더 큰 배열에서 어떤 연산을 수행하기를 원할 때가 있다.

예를 들어, 행렬의 각 행에 상수 벡터를 추가하는 경우이다.

In [ ]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
y = np.array([1, 0, 2])

In [ ]:
print(x)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 2]


In [ ]:
z = x + y
print(z, z.shape)

[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]] (4, 3)


두 개의 배열을 브로드캐스팅하는 것은 다음 규칙을 따른다.

1. 배열의 랭크가 같지 않으면 두 모양이 같은 길이가 될 때까지 배열의 낮은 랭크쪽에 1을 붙인다.
2. 두 배열은 차원에서 크기가 같거나 배열 중 하나의 크기가 1인 경우 차원에서 호환 가능하다고 한다.
3. 배열은 모든 차원에서 호환되면 함께 broadcast 될 수 있다.
4. broadcast후 각 배열은 두 개의 입력 배열의 요소 모양 최대 개수와 동일한 모양을 가진 것 처럼 동작한다.
5. 한 배열의 크기가 1이고 다른 배열의 크기가 1보다 큰 차원에서 첫 번째 배열은 마치 해당 차원을 따라 복사 된 것처럼 작동한다.

ex.
(5, 3) + (3,)
-> (5, 3) + (1, 3)
-> (5, 3) + (5, 3)
-> (5, 3)

In [ ]:
x = np.array([1,2 ,3]).reshape(1, 3)
y = np.array([4, 5]).reshape(1, 2)
print(x, x.shape)
print(y, y.shape)

[[1 2 3]] (1, 3)
[[4 5]] (1, 2)


In [ ]:
# broadcasting 조건에 맞지 않음
print(x + y)

ValueError: ignored

In [ ]:
y = y.swapaxes(0, 1)
print(y, y.shape)

[[4]
 [5]] (2, 1)


In [ ]:
#(1, 3) + (2, 1) -> (2, 3) + (2, 1) -> (2, 3) + (2, 3) -> (2, 3)
print(x + y)

[[5 6 7]
 [6 7 8]]


# Shape 변경

In [ ]:
a = np.arange(24).reshape(2, 3, 4)
print(a, a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [ ]:
a = a.reshape(4, -1)
print(a, a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


In [ ]:
a = a[..., np.newaxis] # newaxis ->  차원 증가
print(a, a.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]] (4, 6, 1)


In [ ]:
a = a.reshape(4, 6)
a = np.expand_dims(a, axis=0) 
# a = np.expand_dims(a, axis=-1) 
print(a, a.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [ ]:
b = a.copy()
print(b, b.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [ ]:
c = np.concatenate((a, b), axis=-1)
print(c, c.shape)

[[[ 0  1  2  3  4  5  0  1  2  3  4  5]
  [ 6  7  8  9 10 11  6  7  8  9 10 11]
  [12 13 14 15 16 17 12 13 14 15 16 17]
  [18 19 20 21 22 23 18 19 20 21 22 23]]] (1, 4, 12)


In [ ]:
c = np.concatenate((a, b), axis=0)
print(c, c.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (2, 4, 6)


In [ ]:
d = np.stack((a, b), axis=-1) # stack사용시 차원을 하나 더 늘림
print(d, d.shape)

[[[[ 0  0]
   [ 1  1]
   [ 2  2]
   [ 3  3]
   [ 4  4]
   [ 5  5]]

  [[ 6  6]
   [ 7  7]
   [ 8  8]
   [ 9  9]
   [10 10]
   [11 11]]

  [[12 12]
   [13 13]
   [14 14]
   [15 15]
   [16 16]
   [17 17]]

  [[18 18]
   [19 19]
   [20 20]
   [21 21]
   [22 22]
   [23 23]]]] (1, 4, 6, 2)


In [ ]:
d = np.stack((a, b), axis=0)
print(d, d.shape)

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]


 [[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]] (2, 1, 4, 6)
