<a href="https://colab.research.google.com/github/wsm9175/DeepLearningStudy/blob/main/sigmoid_and_softmax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sigmoid in Dense

In [6]:
import tensorflow as tf

from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

N, n_feature = 8, 10

x = tf.random.normal(shape=(N, n_feature))

model = Sequential()
model.add(Dense(units=10, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

Y = model(x)


[[0.43900517]
 [0.58683693]
 [0.33634257]
 [0.427994  ]
 [0.75011647]
 [0.8671812 ]
 [0.7084383 ]
 [0.645337  ]]


3-4 Softmax Layers

Code.3-4-1 : IO of Softmax

In [28]:
import tensorflow as tf
from tensorflow.keras.layers import Activation

logit = tf.random.uniform(shape=(2, 5), minval=-10, maxval=10) # -10-10 사이에서 랜덤한 값 생성

softmax_value = Activation('softmax')(logit)
softmax_sum = tf.reduce_sum(softmax_value, axis=1)

print("logits: ", logit.numpy())
print('Probability: ', softmax_value.numpy())
print('Sum of sotfmax values: ', softmax_sum.numpy())

logits:  [[-9.4881935   1.843586   -3.9785457   5.206194   -9.175703  ]
 [-5.9622264  -0.17506123 -7.565632    0.66687393 -3.1710124 ]]
Probability:  [[4.0130431e-07 3.3481363e-02 9.9147845e-05 9.6641845e-01 5.4851273e-07]
 [9.0876844e-04 2.9633784e-01 1.8285342e-04 6.8775684e-01 1.4813649e-02]]
Sum of sotfmax values:  [0.9999999 1.       ]


Code.3-4-2: Softmax in Dense Layers

In [34]:
import tensorflow as tf

from tensorflow.keras.layers import Dense

logit = tf.random.uniform(shape=(8, 5), minval=-10, maxval=10)
dense = Dense(units=8, activation='softmax')

Y = dense(logit)
print(tf.reduce_sum(Y, axis=1))

tf.Tensor(
[0.99999994 1.         0.99999994 1.         1.         1.
 0.99999994 1.        ], shape=(8,), dtype=float32)


3-5: Multi-class Classifiers

Code.3-5-1: Multi-class Classifiers

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential, Model

class MultiClassClassifiers(Model):
  def __init__(self):
    super(MultiClassClassifiers, self).__init__()

    self.model = Sequential()
    self.model.add(Dense(units=10, activation = 'relu'))
    self.model.add(Dense(units=8, activation = 'relu'))
    self.model.add(Dense(units=3, activation='softmax'))
  
  def __call__(self, x):
    Y = self.model(x) 
    return Y

N, n_feature = 8, 10

X = tf.random.normal(shape=(8, 10))
model = MultiClassClassifiers()
output = model(X)
print(output)

print(tf.reduce_sum(output, axis=1))

tf.Tensor(
[[0.2200502  0.40138513 0.37856472]
 [0.16567157 0.58113426 0.2531942 ]
 [0.18437505 0.3768925  0.43873253]
 [0.16242404 0.54044586 0.29713017]
 [0.2341089  0.31767952 0.44821158]
 [0.16346358 0.5460058  0.29053062]
 [0.13579865 0.44065776 0.42354357]
 [0.12104379 0.5260957  0.3528606 ]], shape=(8, 3), dtype=float32)
tf.Tensor(
[1.        1.        1.0000001 1.        1.        1.        1.
 1.0000001], shape=(8,), dtype=float32)
